export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCT_BY_PRICE = "ORDER_PRODUCT_BY_PRICE";

export const HANDLE_CHANGE_CART = "HANDLE_CHANGE_CART";
export const FETCH_CART_ITEM = "FETCH_CART_ITEM"